server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:obsdl;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:db/demo-init.sql

logging:
  level:
    root: INFO
    com.obsdl.master: DEBUG
    com.baomidou.mybatisplus: INFO

obs:
  browser:
#    mode: mock
    mode: real
