server:
  port: 8080

spring:
  application:
    name: obsdl-master
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/obsdl?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      table-underline: true
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    com.obsdl.master: DEBUG
    com.baomidou.mybatisplus: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html

obs:
  browser:
    mode: real


control:
  ros1-setup: /opt/ros/noetic/setup.bash
  ros2-setup: /opt/ros/humble/setup.bash
  log-out: /tmp/rosctl.out
  log-err: /tmp/rosctl.err
  host-for-ws-url: ""
  token-cache-ttl-seconds: 60
